"""GitHub integration: branch, commit, push, PR, Actions."""
from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Dict, Optional, Tuple

import git
from github import Github, GithubException

logger = logging.getLogger(__name__)

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_REPO = os.getenv("GITHUB_REPO", "")          # e.g. "owner/repo"
GITHUB_BASE_BRANCH = os.getenv("GITHUB_BASE_BRANCH", "main")
REPO_LOCAL_PATH = Path(os.getenv("REPO_LOCAL_PATH", "."))


def _gh_client() -> Github:
    if not GITHUB_TOKEN:
        raise RuntimeError("GITHUB_TOKEN environment variable is not set")
    return Github(GITHUB_TOKEN)


def _local_repo() -> git.Repo:
    return git.Repo(REPO_LOCAL_PATH)


# ---------------------------------------------------------------------------
# Create branch, commit files, push
# ---------------------------------------------------------------------------

def push_terraform_branch(
    request_id: str,
    files: Dict[str, str],
    prompt: str,
) -> Tuple[str, str]:
    """
    Create a new git branch, write terraform files, commit, push.
    Returns (branch_name, commit_sha).
    """
    branch_name = f"ai-agent/req-{request_id[:8]}"
    repo = _local_repo()

    # Ensure we start from the base branch
    repo.git.fetch("origin")
    repo.git.checkout(GITHUB_BASE_BRANCH)
    repo.git.pull("origin", GITHUB_BASE_BRANCH)

    # Create and checkout new branch
    repo.git.checkout("-b", branch_name)

    # Write terraform files into terraform/ subdirectory
    tf_dir = REPO_LOCAL_PATH / "terraform"
    tf_dir.mkdir(exist_ok=True)

    written = []
    for filename, content in files.items():
        dest = tf_dir / filename
        dest.write_text(content)
        written.append(str(dest.relative_to(REPO_LOCAL_PATH)))

    repo.index.add(written)
    commit = repo.index.commit(
        f"AI Agent: Generate Terraform infrastructure\n\nRequest: {prompt[:200]}"
    )

    # Push
    repo.git.push("origin", branch_name)

    return branch_name, commit.hexsha


# ---------------------------------------------------------------------------
# Create Pull Request
# ---------------------------------------------------------------------------

def create_pull_request(
    branch_name: str,
    request_id: str,
    prompt: str,
    spec_dict: dict,
    plan_output: str,
    files: Dict[str, str],
) -> str:
    """Create a GitHub PR and return its URL."""
    if not GITHUB_REPO:
        raise RuntimeError("GITHUB_REPO environment variable is not set")

    gh = _gh_client()
    repo = gh.get_repo(GITHUB_REPO)

    resources = spec_dict.get("resources", [])
    region = spec_dict.get("region", "us-east-1")

    # Security warnings
    sg = spec_dict.get("security_group") or {}
    warnings = []
    if sg.get("allow_ssh"):
        warnings.append("⚠️ SSH (port 22) is open to 0.0.0.0/0 — restrict in production.")
    if sg.get("allow_http"):
        warnings.append("⚠️ HTTP (port 80) is open to 0.0.0.0/0.")

    files_section = "\n".join(f"- `terraform/{f}`" for f in files)
    warnings_section = "\n".join(warnings) if warnings else "_None_"
    plan_summary = _extract_plan_summary(plan_output)

    body = f"""## AI DevOps Agent — Infrastructure Request

### User Request
> {prompt}

### Resources to Create
- Region: `{region}`
- Resources: {", ".join(f"`{r}`" for r in resources)}

### Generated Terraform Files
{files_section}

### Terraform Plan Summary
```
{plan_summary}
```

### Security Warnings
{warnings_section}

---
*Request ID: `{request_id}`*
*Generated by AI DevOps Agent*
"""

    pr = repo.create_pull(
        title=f"AI Agent: {prompt[:72]}",
        body=body,
        head=branch_name,
        base=GITHUB_BASE_BRANCH,
    )
    return pr.html_url


def _extract_plan_summary(plan_output: str) -> str:
    """Extract the Plan: X to add line from terraform plan output."""
    for line in plan_output.splitlines():
        if line.strip().startswith("Plan:") or "No changes" in line:
            return line.strip()
    # Return last 20 lines as fallback
    lines = plan_output.strip().splitlines()
    return "\n".join(lines[-20:]) if lines else plan_output[:500]


# ---------------------------------------------------------------------------
# Trigger / monitor GitHub Actions
# ---------------------------------------------------------------------------

def trigger_workflow(branch_name: str, workflow_file: str = "terraform.yml") -> Optional[int]:
    """Trigger the terraform workflow on the branch. Returns run ID or None."""
    if not GITHUB_REPO:
        return None
    try:
        gh = _gh_client()
        repo = gh.get_repo(GITHUB_REPO)
        workflow = repo.get_workflow(workflow_file)
        workflow.create_dispatch(ref=branch_name)
        # Get the latest run
        import time
        time.sleep(3)
        runs = workflow.get_runs(branch=branch_name)
        for run in runs:
            return run.id
    except GithubException as e:
        logger.warning("Could not trigger workflow: %s", e)
    return None


def get_workflow_run_status(run_id: int) -> Optional[str]:
    """Return status of a workflow run."""
    if not GITHUB_REPO:
        return None
    try:
        gh = _gh_client()
        repo = gh.get_repo(GITHUB_REPO)
        run = repo.get_workflow_run(run_id)
        return run.status  # queued, in_progress, completed
    except GithubException:
        return None
